import { Suspense, lazy } from "react";
import { Inter } from 'next/font/google'
import { NavBar } from '@/components/NavBar'
import { Spinner } from '@/components/Spinner'


import './globals.css'
import 'bootstrap/dist/css/bootstrap.min.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const ASSETPREFIX  = process.env.ASSETPREFIX || ''

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          {/* @ts-expect-error Server Component */}
          <NavBar assetPrefix={ASSETPREFIX} />
        </div>

        {/* @ts-expect-error Server Component */}
        <Suspense fallback={<Spinner />}>
          {children}
        </Suspense>
        {/* <div>
          FOOTER PLACEHOLDER
        </div> */}
      </body>
    </html>
  )
}
